language: node_js
node_js:
  - 'stable'
  - '7'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'ramp-webextensions-generator' ]; then cd .. && eval "mv $currentfolder ramp-webextensions-generator" && cd ramp-webextensions-generator; fi
